changed file permission

diff --git a/0x04-loops_conditions_and_parsing/103-dig_the-data b/0x04-loops_conditions_and_parsing/103-dig_the-data
--- a/0x04-loops_conditions_and_parsing/103-dig_the-data
+++ b/0x04-loops_conditions_and_parsing/103-dig_the-data
@@ -1,4 +1,11 @@
 #!/usr/bin/env bash
-# parses an Apache log file and displays the IP and HTTP code for each visitor, along with the number of occurences.
+# Parses an Apache log file and displays the number of occurrences, IP, and HTTP code for each visitor.
 
-awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr
+LOG_FILE="apache-access.log"
+
+if [ ! -f "$LOG_FILE" ]; then
+    echo "Log file $LOG_FILE not found!"
+    exit 1
+fi
+
+awk '{print $1, $9}' "$LOG_FILE" | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
